### ISSUE TITLE
error problem

### ISSUE THREAD

**Issue by myseverus** [lipi12q/TranscriptionNet#2]
Traceback (most recent call last):
  File "C:\anaconda\envs\mdformer\lib\site-packages\pandas\core\indexes\base.py", line 3802, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/20825/Desktop/bioinformations/TranscriptionNet-main/example_run.py", line 28, in <module>
    RNAi_pre_GECs = run_model(num_layers=config.FunDNN_layers,
  File "C:\Users\20825\Desktop\bioinformations\TranscriptionNet-main\FunDNN\Model.py", line 85, in run_model
    test_evaluate(best_model, feature_test, gecs_test)
  File "C:\Users\20825\Desktop\bioinformations\TranscriptionNet-main\FunDNN\train_function.py", line 112, in test_evaluate
    pearson = np.corrcoef(feature_test_predict[i], gecs_test[i])[0, 1]
  File "C:\anaconda\envs\mdformer\lib\site-packages\pandas\core\frame.py", line 3807, in __getitem__
    indexer = self.columns.get_loc(key)
  File "C:\anaconda\envs\mdformer\lib\site-packages\pandas\core\indexes\base.py", line 3804, in get_loc
    raise KeyError(key) from err
KeyError: 0
Hi！This error was generated at the end of the run example_run.py,how to resolve the problem? thank you.

**Comment by lipi12q** [comment]
Hello, I have carefully checked the code, there is no problem with the code, you can check whether it is a problem with the data set. We will communicate if there is any problem later!
